#(EC2 개발 환경용)
version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: barunchuk-frontend-dev
    ports:
      - "3001:3001" 
    networks:
      - barunchuk
    volumes:
      - ./frontend:/app 
      - /app/node_modules # node_modules는 컨테이너 내부에 생성되도록 예외 처리

  backend-node:
    build: ./backend/server
    container_name: barunchuk-backend-node-dev
    ports:
      - "3000:3000"
    networks:
      - barunchuk
    volumes:
      - ./backend/server:/app # EC2의 backend/server 폴더를 컨테이너 /app에 마운트
      - /app/node_modules
      - ./frontend/dist:/app/frontend_dist

  backend-python:
    build: ./backend/fastapi
    container_name: barunchuk-backend-python-dev
    ports:
      - "8000:8000"
    networks:
      - barunchuk
    volumes:
      - ./backend/fastapi:/app # EC2의 backend/fastapi 폴더를 컨테이너 /app에 마운트

networks:
  barunchuk:
    driver: bridge