apiVersion: v1
kind: Service
metadata:
  name: barunchuk-app-service
spec:
  type: NodePort
  selector:
    app: bi-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 32000 
