apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-barunchuk-app-deployment-b
  labels:
    app: fe-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-back
  template:
    metadata:
      labels:
        app: fe-back
    spec:
      containers:
      - name: fe-back
        image: pcheol/barunchuck-backend:latest
        ports:
        - containerPort: 8000
