apiVersion: v1
kind: Service
metadata:
  name: fe-barunchuk-app-service-b
spec:
  type: NodePort
  selector:
    app: fe-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32002
