apiVersion: v1
kind: Service
metadata:
  name: fe-barunchuk-app-service
spec:
  type: NodePort
  selector:
    app: fe-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32001 
