name: Python FASTAPI APP
run-name : ${{ github.workflow }}

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install Dependencies
        run: | 
          cd backend/fastapi
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Uvicorn Server
        run: |
          cd backend/fastapi
          uvicorn app:app --host 0.0.0.0 --port 3000 --reload &
        timeout-minutes: 10

      - name: Stop Uvicorn Server
        run: |
          cd backend/fastapi
          pkill -f uvicorn
          